sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: '0205006'
  alioss:
    # 设置oss的endpoint
    endpoint:
    # 设置oss的bucket名称
    bucket-name: springboot001
